export class Billing {
    woOpenDate: Date;
    customerRef: string;
    workScope: string;
    invoiceTypeId: number;
    invoiceNo: string;
    customerId: number;
    invoiceDate: Date;
    invoiceTime: Date;
    printDate: Date;
    shipDate: Date;
    noofPieces: number;
    employeeId: number;
    employeeName: string;
    revType: number;
    gateStatus: string;
    soldToCustomerId: any;
    soldToSiteId: number;
    shipToCustomerId: any;
    shipToSiteId: number;
    shipToAttention: '';
    managementStructureId: number;
    woType: string;
    notes: string;
    costPlusType: string;
    totalWorkOrder: boolean;
    totalWorkOrderValue: number;
    material: boolean;
    materialValue: number;
    laborOverHead: boolean;
    laborOverHeadValue: number;
    miscCharges: boolean;
    miscChargesValue: number;
    freight: boolean;
    freightValue: number;
    proForma: boolean;
    partialInvoice: boolean;
    costPlusRateCombo: boolean;
    shipViaId: number;
    wayBillRef: string;
    tracking: string;
    currencyId: number;
    salesPerson: string;
    availableCredit: number;
    creditTerm: string;
    shipAccountInfo: string;
    totalWorkOrderCost: number;
    totalWorkOrderCostPlus: number;
    materialCost: number;
    materialCostPlus: number;
    laborOverHeadCost: number;
    laborOverHeadCostPlus: number;
    miscChargesCost: number;
    miscChargesCostPlus: number;
    freightCostPlus: number;
    freightCost: number;
    grandtotal: number;
    constructor() {
        this.woOpenDate = null;
        this.customerRef = '';
        this.workScope = '';
        this.invoiceTypeId = null;
        this.invoiceNo = '';
        this.customerId = null;
        this.invoiceDate = new Date();
        this.invoiceTime = null;
        this.printDate = new Date();
        this.shipDate = new Date();
        this.noofPieces = null;
        this.employeeId = null;
        this.employeeName = '';
        this.revType = null;
        this.gateStatus = null;
        this.soldToCustomerId = null;
        this.soldToSiteId = null;
        this.shipToCustomerId = null;
        this.shipToSiteId = null;
        this.shipToAttention = '';
        this.managementStructureId = 1;
        this.woType = '';
        this.notes = '';
        this.costPlusType = 'Cost Plus';
        this.totalWorkOrder = false;
        this.totalWorkOrderValue = 0;
        this.material = false;
        this.materialValue = null;
        this.laborOverHead = false;
        this.laborOverHeadValue = null;
        this.miscCharges = false;
        this.miscChargesValue = null;
        this.proForma = false;
        this.partialInvoice = false;
        this.costPlusRateCombo = false;
        this.shipViaId = null;
        this.wayBillRef = '';
        this.tracking = '';
        this.currencyId = null;
        this.salesPerson = '';
        this.availableCredit = null;
        this.creditTerm = '';
        this.shipAccountInfo = '';
        this.totalWorkOrderCost = null;
        this.totalWorkOrderCostPlus = null;
        this.materialCost = null;
        this.materialCostPlus = null;
        this.laborOverHeadCost = null;
        this.laborOverHeadCostPlus = null;
        this.miscChargesCost = null;
        this.miscChargesCostPlus = null;
        this.grandtotal = null;
    }
}