export class SalesOrderBillingAndInvoicing {
    sOBillingInvoicingId: number;
    salesOrderId: number;
    salesOrderPartId: number;
    itemMasterId: number;
    invoiceTypeId: number;
    invoiceNo: string;
    customerId: number;
    masterCompanyId: number;
    invoiceDate: Date;
    invoiceTime: string;
    printDate: Date;
    shipDate: Date;
    noofPieces: number;
    revType: number;
    currencyId: number;
    gateStatus: string;
    soldToCustomerId: number;
    soldToSiteId: number;
    shipToCustomerId: number;
    shipToSiteId: number;
    shipToAttention: string;
    isProForma: boolean = false;
    shipViaId: number;
    wayBillRef: string;
    tracking: string;
    availableCredit: number;
    createdBy: string;
    updatedBy: string;
    isActive: boolean;
    isDeleted: boolean;
    createdDate: Date;
    updatedDate: Date;
    billToCustomerId: number;
    billToSiteId: number;
    employeeName: string;
    salesPersonId:number;
    salesPerson:string;
    customerRef:string;
    openDate: Date;
}
// {
//     soBillingInvoicingId: 0;
//     salesOrderId: 0;
//     salesOrderPartId: 0;
//     itemMasterId: 0;
//     invoiceTypeId: 0;
//     invoiceNo: string;
//     customerId: 0;
//     invoiceDate: Date;
//     invoiceTime: string;
//     printDate: Date;
//     shipDate: Date;
//     noofPieces: 0;
//     employeeId: 0;
//     revType: 0;
//     gateStatus: string;
//     soldToCustomerId: 0;
//     soldToSiteId: 0;
//     shipToCustomerId: 0;
//     shipToSiteId: 0;
//     shipToAttention: string;
//     managementStructureId: 0;
//     managementEmpId: 0;
//     notes: string;
//     costPlusType: string;
//     isTotalSalesOrder: boolean;
//     totalSalesOrderValue: 0;
//     isMiscCharges: boolean;
//     miscChargesValue: 0;
//     isProForma: boolean;
//     isPartialInvoice: boolean;
//     isCostPlusRateCombo: boolean;
//     shipViaId: 0;
//     wayBillRef: string;
//     tracking: string;
//     currencyId: 0;
//     availableCredit: 0;
//     totalSalesOrderCost: 0;
//     totalSalesOrderCostPlus: 0;
//     miscChargesCost: 0;
//     miscChargesCostPlus: 0;
//     grandTotal: 0;
//     masterCompanyId: 0;
//     createdBy: string;
//     createdDate: Date;
//     updatedBy: string;
//     updatedDate: Date;
//     isActive: boolean;
//     isDeleted: boolean;
// }