export enum SalesOrderActionType {
    None = 0,
    ViewQuote = 1,
    MakePayment = 2,
    NewSalesOrder = 3,
    PrintSalesOrder = 4,
    PrintPickTicket = 5,
    PrintLabels = 6,
    EmailSalesOrder = 7,
    MakeDuplicate = 8,
    SalesRegister = 9,
    Activity = 10,
    AuthorizeReturn = 11,
    Refund = 12,
    CancelSalesOrder = 13,
    CloseSalesOrder = 14,
    PartialPayment = 15,
    CashSales = 16,
    Deposit = 17,
    Email = 18,
    Memo = 19,
    Phone = 20,
    Text=21
}